//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace bug_tracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bugs
    {
        public int rowid { get; set; }
        public string bid { get; set; }
        public string bsummary { get; set; }
        public string bcreator { get; set; }
        public string bstatus_id { get; set; }
        public string bpriority_id { get; set; }
        public Nullable<System.DateTime> binit_time { get; set; }
        public Nullable<System.DateTime> bmodified_time { get; set; }
        public string bpid { get; set; }
        public string basignee { get; set; }
        public string bdescription { get; set; }
    }
}
