//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace bug_tracker.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bug_trackerEntities : DbContext
    {
        public bug_trackerEntities()
            : base("name=bug_trackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<projects> projects { get; set; }
        public virtual DbSet<bugs> bugs { get; set; }
        public virtual DbSet<priorities> priorities { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<UserMessage> UserMessage { get; set; }
        public virtual DbSet<AppCode> AppCode { get; set; }
    }
}
