//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace bug_tracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int rowid { get; set; }
        public string uid { get; set; }
        public string umno { get; set; }
        public string uname { get; set; }
        public string upassword { get; set; }
        public string uphone { get; set; }
        public string uemail { get; set; }
        public string urole { get; set; }
        public Nullable<System.DateTime> ubirthday { get; set; }
        public string remark { get; set; }
        public string varify_code { get; set; }
        public bool isvarify { get; set; }
        public Nullable<System.DateTime> uinit_time { get; set; }
        public Nullable<System.DateTime> umodified_time { get; set; }
    }
}
